### PR TITLE
V0.0.373

### PR DESCRIPTION
**Pull request by martinswiderski**
Documentation
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/moonlit-sky%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/26248105%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/martinswiderski/valdi/pull/11%23issuecomment-289197604%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-03-25T08%3A22%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/26248105%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/moonlit-sky%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222017-03-25T08%3A41%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/26248105%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/moonlit-sky%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222017-03-25T08%3A44%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/26248105%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/moonlit-sky%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/martinswiderski/valdi/pull/11%23issuecomment-289197604%22%2C%20%22https%3A//github.com/martinswiderski/valdi/pull/11%23issuecomment-289198339%22%2C%20%22https%3A//github.com/martinswiderski/valdi/pull/11%23issuecomment-289198530%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/moonlit-sky'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/martinswiderski/valdi/pull/11#issuecomment-289197604'>General Comment</a></b>
- <a href='https://github.com/moonlit-sky'></a> :shipit:
- <a href='https://github.com/moonlit-sky'></a> :shipit::gun:

<a href='https://www.codereviewhub.com/martinswiderski/valdi/pull/11?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/martinswiderski/valdi/pull/11?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/martinswiderski/valdi/pull/11?approve=0'></a>&nbsp;<a href='https://github.com/martinswiderski/valdi/pull/11'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by martinswiderski** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/martinswiderski/valdi/pull/11'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by moonlit-sky** [comment]
:shipit:

**Comment by moonlit-sky** [comment]
:shipit::gun:

**Comment by moonlit-sky** [comment]
:shipit:

**Pull request merged**
